#! /bin/sh

# achtung: vorher Sonderzeichen in Dateinamen eliminieren (replace-space):
# - Leerzeichen ')'
# - Öffnende Klammer '('
# - Schließende Klammer ')'
# - Kaufmannsund '&'

# vollständiges Datum: 2000-04-21
find . | sed -e 's/\(.*\/\)\(.*\)\(.\)\([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\)\(\..*\)$/mv & \1\4\3\2\5/' -e 'tx' -e 'd' -e ':x' | sh

# Jahr und Monat
find . | sed -e 's/\(.*\/\)\(.*\)\(.\)\([0-9][0-9][0-9][0-9]-[0-9][0-9]\)\(\..*\)$/mv & \1\4\3\2\5/' -e 'tx' -e 'd' -e ':x' | sh

# nur Jahr
find . | sed -e 's/\(.*\/\)\(.*\)\(.\)\([0-9][0-9][0-9][0-9]\)\(\..*\)$/mv & \1\4\3\2\5/' -e 'tx' -e 'd' -e ':x' | sh

# statt "| sh" kann man zur Probe " > file" schreiben.