#! /bin/sh

# --- stats ---
# shows statistics about total number of code-lines and number of classes

# assert correct usage
if [ "$1" != "-d" ] || [ "$2" == "" ]
  then
    echo "usage: stats -d rootdir ext1 ext2 ext3 ..."
    exit 0
fi

# save rootdir parameter
ROOTDIR=$2

# print stats for *
echo "type \t #files \t #lines" 
FILELIST=`find $ROOTDIR -type f`
FILES=`echo $FILELIST | wc -w`
LINES=`cat "$FILELIST" | wc -l`
echo "* \t $FILES \t $LINES"

# print stats for user patterns
while [ "$3" != "" ]
  do
    FILES="0"
    LINES="0"
    FILELIST=`find $ROOTDIR -type f -name $3`
    if [ "$FILELIST" != "" ]
      then
        FILES=`echo $FILELIST | wc -w`
        LINES=`cat $FILELIST | wc -l`
    fi
    echo "$3 \t $FILES \t $LINES"
    shift
done

exit 0
